# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DgVWOYh5h02ZCgIaQZPYKkhWvj0F9ddY
"""

pip install gensim

from gensim.summarization import summarize

def text_summarization(text, ratio=0.2):
    """
    Function to perform text summarization using Gensim.

    Parameters:
        text (str): The input text to be summarized.
        ratio (float): The ratio of the original text to be retained in the summary (default is 0.2).

    Returns:
        summary (str): The summarized text.
    """
    summary = summarize(text, ratio=ratio)
    return summary

if __name__ == "__main__":
    # Example text to be summarized
    input_text = """
    Gensim is a Python library for topic modelling, document indexing, and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP) and information retrieval (IR) community.
    Gensim is implemented in Python and Cython.
    """

    # Perform text summarization
    summary = text_summarization(input_text)

    # Print the original text and the summary
    print("Original Text:")
    print(input_text)
    print("\nSummary:")
    print(summary)

